### ISSUE TITLE
Add support for Umbraco 10

### ISSUE THREAD

**Issue by abjerner** [skybrud/Skybrud.Umbraco.Redirects#137]
### TODOs

- [x] Update project to build against `10.0.0-rc1`
- [x] #138
- [x] Support custom backoffice URLs - see https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/140
- [ ] <s>Update project to build against `10.0.0-rc2`</s>
- [x] Update project to build against `10.0.0-rc3`
- [x] Update project to build against `10.0.0` (once released)
